MODEL:
  TYPE: vssm
  NAME: vssm1_small_0229
  DROP_PATH_RATE: 0.3
  VSSM:
    EMBED_DIM: 96
    DEPTHS: [ 2, 2, 15, 2 ]
    SSM_D_STATE: 1
    SSM_DT_RANK: "auto"
    SSM_RATIO: 2.0
    SSM_CONV: 3
    SSM_CONV_BIAS: false
    SSM_FORWARDTYPE: "v3noz"
    MLP_RATIO: 4.0
    DOWNSAMPLE: "v3"
    PATCHEMBED: "v2"

TRAIN:
  USE_CHECKPOINT: True

# 50.4 + 8.6 + 90min/e + 36G