MODEL:
  TYPE: vssm
  NAME: vssm1_tiny_0213
  DROP_PATH_RATE: 0.2
  VSSM:
    EMBED_DIM: 64
    DEPTHS: [3, 3, 12, 3] # 26 + 4.3
    SSM_D_STATE: 1
    SSM_DT_RANK: "auto"
    SSM_RATIO: 2.0
    SSM_CONV: -1
    MLP_RATIO: 4.0
    DOWNSAMPLE: "v3"
    PATCHEMBED: "v1"
