MODEL:
  TYPE: vssm
  NAME: vssm1_tiny_0317
  DROP_PATH_RATE: 0.2
  VSSM:
    EMBED_DIM: 96 # 128
    DEPTHS: [2, 2, 5, 2] # [ 3,3,27,3 ]
    SSM_D_STATE: 1
    SSM_DT_RANK: "auto"
    SSM_RATIO: 2.0
    SSM_CONV: -1 # 3
    SSM_CONV_BIAS: false
    SSM_FORWARDTYPE: "xv6"
    MLP_RATIO: 4.0
    DOWNSAMPLE: "v2" # "v3"
    PATCHEMBED: "v1" # "v2"
