MODEL:
  TYPE: vssm
  NAME: vssm1_tiny_0211v1
  DROP_PATH_RATE: 0.2
  VSSM:
    EMBED_DIM: 96
    DEPTHS: [ 2, 2, 4, 2 ]
    SSM_D_STATE: 2
    SSM_DT_RANK: "auto"
    SSM_RATIO: 2.0
    SSM_CONV: -1
    MLP_RATIO: 4.0
    DOWNSAMPLE: "v2"
    PATCHEMBED: "v1"

